---
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
MD013: false

# https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md026
MD026:
  punctuation: ".,;:"

# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033---inline-html
MD033: false
