language: ruby

install:
  - bundle install --jobs=3 --retry=3
  - gem install html-proofer

script:
  - bundler exec github-pages versions
  - jekyll build
  - htmlproofer ./_site --disable-external --check-html

# caching bundler gem packages will speed up build
cache: bundler

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

# Disable email notifications about builds
notifications:
  email: false