---
language: ruby

install:
  - pip install --user yamllint
  - bundle install --jobs=3 --retry=3
  - gem install html-proofer -v 3.19.2

script:
  - yamllint .
  - bundle exec github-pages versions
  - bundle exec jekyll build
  - htmlproofer ./_site --disable-external --check-html

# caching bundler gem packages will speed up build
cache: bundler

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

# Disable email notifications about builds
notifications:
  email: false
