#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Telepost

# Name of the author
author: Roman Nikolaev

# Short bio or description (displayed in the header)
description: Лучший отложенный постинг для Telegram

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://app.telepost.me/assets/favicons/icon-194x194.png

# Github Issues information
github-issues:
  username: Telepost-me
  repo: support

# Telepost Info
telepost:
  site:
    name: Telepost.me
    url: https://telepost.me/
  web-app:
    name: app.telepost.me
    url: https://app.telepost.me/
  bot:
    name: "@TelepostBot"
    url: https://t.me/TelepostBot
  support-user:
    name: "@TelepostSupport"
    url: https://t.me/TelepostSupport
  support-chat:
    name: Telepost чат
    url: https://t.me/joinchat/KL_EBhbpHVuFmf_LDAHmTQ

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  telegram: TelepostBot
  dribbble:
  email: telepost.me@gmail.com
  facebook:
  flickr:
  github: Telepost-me
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: https://telepost-me.github.io
enforce_ssl: https://telepost-me.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

relative_links:
  enabled: true

permalink: /:categories/:title/

# The release of Jekyll Now that you're using
version: v3.9.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links

include: ['_pages']

paginate: 3
paginate_path: /faq/all/page:num/

pagination-text:
  prev: "&laquo; Назад"
  next: "Вперед &raquo;"
  open: "Открыть пост"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor

