---

version: "{build}"

skip_tags: true

skip_commits:
  files:
    - .github/*
    - .travis.yml
    - README.md
    - LICENSE

platform: Any CPU

build_script:
  - sh: >-
      bundle install --jobs=3 --retry=3
      bundle exec jekyll build

on_success:
  - sh: >-
      gem install html-proofer
      htmlproofer ./_site --disable-external --check-html
