---
version: '3.3'
services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - './:/srv/jekyll'
    ports:
      - '4000:4000'
      - '35729:35729'
    command: jekyll serve --incremental --livereload --force_polling
