---
name: ${DOCKER_COMPOSE_NAME}

services:
  docusaurus-run:
    image: ${DOCKER_COMPOSE_DOCUSAURUS_IMAGE}
    container_name: ${DOCKER_COMPOSE_DOCUSAURUS_CONTAINER}
    ports:
      - ${DOCKER_COMPOSE_DOCUSAURUS_PORT}:3000
    volumes:
      - ${PWD}/:${DOCKER_COMPOSE_DOCUSAURUS_PATH}/
    working_dir: ${DOCKER_COMPOSE_DOCUSAURUS_PATH}
    environment:
      FORCE_COLOR: 1
    command:
      - bash
      - -c
      - |
        npm install
        npm run clear
        npm run build
        npm run ${DOCKER_COMPOSE_DOCUSAURUS_RUN_MODE} ${DOCKER_COMPOSE_DOCUSAURUS_OPTIONS}

  yaml-lint:
    image: ${DOCKER_COMPOSE_YAMLLINT_IMAGE}
    container_name: ${DOCKER_COMPOSE_YAMLLINT_CONTAINER}
    volumes:
      - ${PWD}/:${DOCKER_COMPOSE_YAMLLINT_PATH}
    working_dir: ${DOCKER_COMPOSE_YAMLLINT_PATH}
    environment:
      FORCE_COLOR: 1
    command: ${DOCKER_COMPOSE_YAMLLINT_OPTIONS} .

  markdown-lint:
    image: ${DOCKER_COMPOSE_MARKDOWNLINT_IMAGE}
    container_name: ${DOCKER_COMPOSE_MARKDOWNLINT_CONTAINER}
    volumes:
      - ${PWD}/:${DOCKER_COMPOSE_MARKDOWNLINT_PATH}
    working_dir: ${DOCKER_COMPOSE_MARKDOWNLINT_PATH}
    environment:
      FORCE_COLOR: 1
    command: markdownlint ${DOCKER_COMPOSE_MARKDOWNLINT_OPTIONS}
