---
# See .env for variables

name: ${DOCKER_COMPOSE_NAME}
services:
  jekyll-site:
    image: ${DOCKER_COMPOSE_JEKYLL_IMAGE}
    container_name: ${DOCKER_COMPOSE_JEKYLL_CONTAINER}
    volumes:
      - ./:${DOCKER_COMPOSE_JEKYLL_PATH}
    ports:
      - ${DOCKER_COMPOSE_JEKYLL_PORT}:4000
      - 35729:35729
    command: jekyll serve ${DOCKER_COMPOSE_JEKYLL_OPTIONS}

  yaml-lint:
    image: ${DOCKER_COMPOSE_YAMLLINT_IMAGE}
    container_name: ${DOCKER_COMPOSE_YAMLLINT_CONTAINER}
    volumes:
      - ./:${DOCKER_COMPOSE_YAMLLINT_PATH}
    working_dir: ${DOCKER_COMPOSE_YAMLLINT_PATH}
    command: ${DOCKER_COMPOSE_YAMLLINT_OPTIONS} .

  html-proofer:
    image: ${DOCKER_COMPOSE_HTMLPROOFER_LOCAL_IMAGE}
    container_name: ${DOCKER_COMPOSE_HTMLPROOFER_CONTAINER}
    # Build image for linting purpose only!
    build:
      context: .
      dockerfile_inline: |
        FROM ${DOCKER_COMPOSE_JEKYLL_IMAGE} as jekyll
        COPY . ${DOCKER_COMPOSE_JEKYLL_PATH}
        RUN jekyll build

        FROM ${DOCKER_COMPOSE_HTMLPROOFER_IMAGE}
        COPY --from=jekyll ${DOCKER_COMPOSE_JEKYLL_PATH}/_site ${DOCKER_COMPOSE_HTMLPROOFER_PATH}
    command: ${DOCKER_COMPOSE_HTMLPROOFER_PATH} ${DOCKER_COMPOSE_HTMLPROOFER_OPTIONS}
