---
# Super Linter GitHub Actions
name: Checks

# Start the job on all push
on: push  # yamllint disable-line rule:truthy

jobs:
  # https://docusaurus.io/docs/deployment#deploying-to-github-pages
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: npm install-clean
      - name: Build website
        run: npm run build
